export const HOME_CLOSE_CARD = 'HOME_CLOSE_CARD';
export const HOME_OPEN_SOLAR = 'HOME_OPEN_SOLAR';
export const HOME_OPEN_WELLS = 'HOME_OPEN_WELLS';
export const HOME_OPEN_PILES = 'HOME_OPEN_PILES';
export const HOME_GET_TEMP_BEGIN = 'HOME_GET_TEMP_BEGIN';
export const HOME_GET_TEMP_SUCCESS = 'HOME_GET_TEMP_SUCCESS';
export const HOME_GET_TEMP_FAILURE = 'HOME_GET_TEMP_FAILURE';
export const HOME_GET_TEMP_DISMISS_ERROR = 'HOME_GET_TEMP_DISMISS_ERROR';
